### ISSUE TITLE
Counterpart PR:  RM ANOVA: clear environment of function in referenceGrid before saving it to state #4323 

### ISSUE THREAD

**Issue by AlexanderLyNL** [jasp-stats/jaspAnova#14]
https://github.com/jasp-stats/jasp-desktop/pull/4323

**Comment by vandenman** [comment]
Let's wait with implementing this until we know whether this can be resolved within emmeans. If it can be implemented in emmeans before the next release, great. Otherwise, I'll also add the changes from  jasp-stats/jasp-desktop#4323 here.

**Comment by vandenman** [comment]
Following the discussion at https://github.com/rvlenth/emmeans/issues/232, I hope that this change doesn't need to be copied over and instead, we can use emmeans 1.5.2.

**Comment by TimKDJ** [comment]
Yeah that looks hopeful
