### ISSUE TITLE
Implement equivalent change "RM (B)ANOVA: fix names in long format data set"

### ISSUE THREAD

**Issue by TimKDJ** [jasp-stats/jaspAnova#2]
See https://github.com/jasp-stats/jasp-desktop/pull/4086

**Comment by vandenman** [comment]
I think this is done already, compare e.g., https://github.com/jasp-stats/jaspAnova/blob/master/R/anovarepeatedmeasures.R#L231 and https://github.com/jasp-stats/jasp-desktop/pull/4086/files
